"use client";
import { Icon } from "@iconify/react";
import { Badge } from "@/components/ui/badge";
import { campaignImage } from "@/lib/dashboard/campaignMedia";
function v(d:any,...k:string[]){for(const x of k)if(d?.[x]!=null)return d[x];}
export function donationAmount(d:any){return Number(v(d,"amount","donation_amount","total")||0)}
export function donationStatus(d:any){return String(v(d,"payment_status","status","donation_status")||"Pending")}
export function donationCampaign(d:any){return d?.campaign?.title||v(d,"campaign_title","title")||`Campaign #${v(d,"campaign_id")||"—"}`}
export function donationImage(d:any){return campaignImage(d)}
export function donationDate(d:any){const x=v(d,"created_at","date_created","date","created");if(!x)return "—";const z=new Date(x);return Number.isNaN(z.getTime())?String(x):z.toLocaleString(undefined,{year:"numeric",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}
export default function DonationDetailsModal({donation,onClose}:{donation:any,onClose:()=>void}){const status=donationStatus(donation),amount=donationAmount(donation),img=donationImage(donation);return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/75 p-4" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="w-full max-w-[520px] overflow-hidden rounded-xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b px-5 py-4"><h3 className="flex items-center gap-2 font-semibold"><Icon icon="solar:hand-heart-line-duotone" className="text-xl"/> Donation Details</h3><button onClick={onClose} className="rounded-lg border p-2 text-darklink"><Icon icon="solar:close-circle-linear"/></button></div><div className="space-y-4 bg-lightgray/40 p-5"><div className="flex items-center justify-between text-xs text-darklink"><span>Created on {donationDate(donation)}</span><Badge variant={["paid","completed","success","successful"].includes(status.toLowerCase())?"lightSuccess":"lightWarning"}>{status}</Badge></div><div className="flex items-center gap-3 rounded-lg bg-white p-3">{img?<img src={String(img)} alt="" className="h-14 w-14 rounded-md object-cover"/>:<div className="h-14 w-14 rounded-md bg-lightgray"/>}<div><div className="font-medium">{donationCampaign(donation)}</div><div className="mt-1 text-sm text-darklink">by {donation?.fundraiser?.name||donation?.fundraiser_name||donation?.campaign?.fundraiser_name||"Fundraiser"}</div></div></div><div className="rounded-lg bg-white p-4"><p className="text-sm text-darklink">Donation Amount</p><div className="mt-1 text-2xl font-semibold">${amount.toFixed(2)}</div></div><div className="rounded-lg bg-white p-4"><div className="flex justify-between"><b>Payment</b><Badge variant={["paid","completed","success","successful"].includes(status.toLowerCase())?"lightSuccess":"lightWarning"}>{status}</Badge></div><div className="mt-4 space-y-3 rounded-md border p-3 text-sm"><div className="flex justify-between"><span className="text-darklink">Donation Amount</span><span>${amount.toFixed(2)}</span></div><div className="flex justify-between font-semibold"><span>Total</span><span>${amount.toFixed(2)}</span></div></div></div></div></div></div>}
