"use client";
import { useEffect, useMemo, useState } from "react";
import CardBox from "@/app/components/shared/CardBox";
import { Badge } from "@/components/ui/badge";
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from "@/components/ui/table";
import { currentUserId,dashboardApi,dashboardRows } from "@/lib/dashboard/api";
import DatePresetSelect from "@/app/components/growfund/shared/DatePresetSelect";
import { isDateInRange, type DateRangeKey } from "@/lib/dashboard/dateRanges";
import { campaignImage } from "@/lib/dashboard/campaignMedia";
function val(d:any,...keys:string[]){for(const k of keys){if(d?.[k]!=null)return d[k];}return undefined;}
function rawDate(d:any){return val(d,"created_at","date_created","date","created");}
export default function DonorDonations(){const[rows,setRows]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[dateRange,setDateRange]=useState<DateRangeKey>("this_year");useEffect(()=>{(async()=>{try{const id=currentUserId();const data=id?await dashboardApi(`donor/${id}/donations?page=1&per_page=100&orderby=id&order=desc`):await dashboardApi("donations/paginated?page=1&per_page=100&orderby=id&order=desc");setRows(dashboardRows(data));}catch(e){setError(e instanceof Error?e.message:"Unable to load donations.");}finally{setLoading(false);}})();},[]);const visibleRows=useMemo(()=>rows.filter(d=>isDateInRange(rawDate(d),dateRange)),[rows,dateRange]);return <CardBox><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h5 className="card-title">My Donations</h5><p className="mt-1 text-sm text-darklink">Your donation history. Administrative donation controls are not available in the donor dashboard.</p></div><DatePresetSelect value={dateRange} onChange={setDateRange}/></div>{error&&<div className="mt-5 rounded-md border border-error/30 bg-lighterror px-4 py-3 text-sm text-error">{error}</div>}<div className="mt-5 overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Donation</TableHead><TableHead>Campaign</TableHead><TableHead>Amount</TableHead><TableHead>Status</TableHead><TableHead>Date</TableHead></TableRow></TableHeader><TableBody>{loading?<TableRow><TableCell colSpan={5} className="py-10 text-center text-darklink">Loading donations…</TableCell></TableRow>:visibleRows.length?visibleRows.map((d,i)=>{const status=String(val(d,"payment_status","status")??"unknown");const raw=rawDate(d);const date=raw?new Date(raw):null;return <TableRow key={d?.id??i}><TableCell className="font-medium">#{val(d,"id","donation_id")??"—"}</TableCell><TableCell><div className="flex items-center gap-3">{campaignImage(d)?<img src={campaignImage(d)} alt="" className="h-10 w-10 rounded-md object-cover"/>:<span className="h-10 w-10 shrink-0 rounded-md bg-lightgray"/>}<span>{d?.campaign?.title??val(d,"campaign_title","title")??`Campaign #${val(d,"campaign_id")??"—"}`}</span></div></TableCell><TableCell>${Number(val(d,"amount","donation_amount","total")??0).toFixed(2)}</TableCell><TableCell><Badge variant={["paid","completed","successful","success"].includes(status.toLowerCase())?"lightSuccess":"lightPrimary"}>{status}</Badge></TableCell><TableCell>{date&&!Number.isNaN(date.getTime())?date.toLocaleDateString():"—"}</TableCell></TableRow>}):<TableRow><TableCell colSpan={5} className="py-10 text-center text-darklink">No donations found for this period.</TableCell></TableRow>}</TableBody></Table></div></CardBox>}
