"use client";
import { useEffect,useState } from "react";
import { Icon } from "@iconify/react";
import { Button } from "@/components/ui/button";
import { DropdownMenu,DropdownMenuTrigger,DropdownMenuContent } from "@/components/ui/dropdown-menu";
import Image from "next/image";
import { dashboardRole,savedDashboardUser } from "@/lib/dashboard/roles";

const SideProfile=()=>{const[user,setUser]=useState<any>(null);useEffect(()=>setUser(savedDashboardUser()),[]);const role=dashboardRole(user);const name=[user?.first_name,user?.last_name].filter(Boolean).join(" ")||user?.display_name||user?.username||"User";const logout=()=>{localStorage.removeItem("access_token");localStorage.removeItem("refresh_token");localStorage.removeItem("auth_user");window.dispatchEvent(new Event("hiilbox-auth-changed"));window.location.href="/login";};return <div className="relative group/menu"><DropdownMenu><DropdownMenuTrigger asChild><span className="h-10 w-10 mx-auto hover:text-primary hover:bg-lightprimary rounded-full flex justify-center items-center cursor-pointer group-hover/menu:bg-lightprimary group-hover/menu:text-primary"><Image src={user?.avatar_url||"/images/profile/user-1.jpg"} alt="profile" height="40" width="40" className="rounded-full mx-auto cursor-pointer border border-dashed border-transparent hover:border-primary p-0.5"/></span></DropdownMenuTrigger><DropdownMenuContent className="w-screen sm:w-[360px] py-6 !shadow-lg rounded-sm"><div className="px-6"><h3 className="text-lg font-semibold text-ld">User Profile</h3><div className="flex items-center gap-6 pb-5 border-b dark:border-darkborder mt-5 mb-3"><Image src={user?.avatar_url||"/images/profile/user-1.jpg"} alt="profile" height="80" width="80" className="rounded-full"/><div className="min-w-0"><h5 className="card-title truncate">{name}</h5><span className="card-subtitle capitalize">{role}</span>{user?.email&&<p className="card-subtitle mb-0 mt-1 flex items-center truncate"><Icon icon="solar:mailbox-line-duotone" className="text-base me-1"/>{user.email}</p>}</div></div></div><div className="pt-4 px-6"><Button onClick={logout} className="w-full rounded-full">Logout</Button></div></DropdownMenuContent></DropdownMenu></div>};
export default SideProfile;
