"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import CardBox from "@/app/components/shared/CardBox";
import { Button } from "@/components/ui/button";
import { Icon } from "@iconify/react";
import { adminApi,rowsFrom } from "./adminApi";

export default function AdminDashboardOverview(){
  const [stats,setStats]=useState({campaigns:0,donations:0,donors:0,fundraisers:0}); const[loading,setLoading]=useState(true);const[error,setError]=useState("");
  useEffect(()=>{(async()=>{try{const [c,d,doa,f]=await Promise.allSettled([adminApi("campaigns?page=1&per_page=100&status=all"),adminApi("donations/paginated?page=1&per_page=100"),adminApi("donors/paginated?page=1&per_page=100"),adminApi("fundraisers/paginated?page=1&per_page=100")]);const count=(x:PromiseSettledResult<any>)=>{if(x.status!=="fulfilled")return 0;const v=x.value;const total=Number(v?.paginated?.total??v?.data?.total??v?.data?.data?.total??v?.total);return Number.isFinite(total)&&total>=0?total:rowsFrom(v).length;};setStats({campaigns:count(c),donations:count(d),donors:count(doa),fundraisers:count(f)});}catch(e){setError(e instanceof Error?e.message:"Unable to load admin overview.");}finally{setLoading(false);}})();},[]);
  const cards=[["Campaigns",stats.campaigns,"solar:flag-2-line-duotone","/dashboard/campaigns"],["Donations",stats.donations,"solar:hand-money-line-duotone","/dashboard/donations"],["Donors",stats.donors,"solar:users-group-rounded-line-duotone","/dashboard/donors"],["Fundraisers",stats.fundraisers,"solar:user-heart-rounded-line-duotone","/dashboard/fundraisers"]];
  return <div className="space-y-7">{error&&<div className="rounded-md border border-error/30 bg-lighterror px-4 py-3 text-sm text-error">{error}</div>}<CardBox className="bg-primary"><h4 className="text-xl text-white">Administrator Dashboard</h4><p className="mt-1 text-sm font-medium text-white/90">Manage GrowFund campaigns, donations, donors, fundraisers and withdrawal requests.</p></CardBox><div className="grid grid-cols-12 gap-7">{cards.map(([l,v,i,u])=><CardBox key={String(l)} className="col-span-12 sm:col-span-6 xl:col-span-3"><div className="flex items-center justify-between"><div><p className="text-sm text-darklink">{l}</p><h4 className="mt-2 text-2xl font-semibold">{loading?"…":v}</h4></div><span className="flex h-12 w-12 items-center justify-center rounded-full bg-lightprimary text-primary"><Icon icon={String(i)} height={25}/></span></div><Button asChild variant="outline" size="sm" className="mt-5"><Link href={String(u)}>Manage {String(l).toLowerCase()}</Link></Button></CardBox>)}</div><CardBox><div className="flex flex-wrap gap-3"><Button asChild><Link href="/dashboard/withdrawals">Withdrawal requests</Link></Button><Button asChild variant="outline"><Link href="/dashboard/campaigns">Campaign moderation</Link></Button><Button asChild variant="outline"><Link href="/dashboard/donations">Donation records</Link></Button></div></CardBox></div>
}
