"use client";
import { useCallback, useEffect, useState } from "react";
import CardBox from "@/app/components/shared/CardBox";
import { Badge } from "@/components/ui/badge";
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from "@/components/ui/table";
import { currentUserId,dashboardApi,dashboardRows } from "@/lib/dashboard/api";
import DatePresetSelect from "@/app/components/growfund/shared/DatePresetSelect";
import { dateRangeParams, type DateRangeKey } from "@/lib/dashboard/dateRanges";
function pick(r:any,...keys:string[]){for(const k of keys){if(r?.[k]!=null)return r[k];}return undefined;}
export default function FundraiserWithdrawals(){
  const[rows,setRows]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[dateRange,setDateRange]=useState<DateRangeKey>("this_year");
  const load=useCallback(async()=>{const id=currentUserId();if(!id){setError("Unable to identify your fundraiser account.");setLoading(false);return;}setLoading(true);setError("");try{const range=dateRangeParams(dateRange);const q=new URLSearchParams({fundraiser_id:String(id),page:"1",per_page:"100",orderby:"id",order:"desc",...range});const data=await dashboardApi(`fundraiser/withdrawal/requests/paginated?${q}`);setRows(dashboardRows(data));}catch(e){setError(e instanceof Error?e.message:"Unable to load withdrawals.");}finally{setLoading(false);}},[dateRange]);
  useEffect(()=>{void load();},[load]);
  return <CardBox><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h5 className="card-title">My withdrawal requests</h5><p className="mt-1 text-sm text-darklink">Track requests sent from your wallet. Approval and decline controls are reserved for administrators.</p></div><DatePresetSelect value={dateRange} onChange={setDateRange}/></div>{error&&<div className="mt-5 rounded-md border border-error/30 bg-lighterror px-4 py-3 text-sm text-error">{error}</div>}<div className="mt-5 overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Request</TableHead><TableHead>Amount</TableHead><TableHead>Method</TableHead><TableHead>Status</TableHead><TableHead>Date</TableHead><TableHead>Note</TableHead></TableRow></TableHeader><TableBody>{loading?<TableRow><TableCell colSpan={6} className="py-10 text-center text-darklink">Loading withdrawals…</TableCell></TableRow>:rows.length?rows.map((r,i)=>{const status=String(pick(r,"status","request_status")??"pending");const raw=pick(r,"created_at","date_created","created","date");const d=raw?new Date(raw):null;return <TableRow key={pick(r,"id","withdrawal_request_id")??i}><TableCell className="font-medium">#{pick(r,"id","withdrawal_request_id")??"—"}</TableCell><TableCell>${Number(pick(r,"amount","withdrawal_amount")??0).toFixed(2)}</TableCell><TableCell>{String(pick(r,"method","payment_method")??"—")}</TableCell><TableCell><Badge variant={status.toLowerCase()==="approved"?"lightSuccess":status.toLowerCase()==="declined"?"lightError":"lightWarning"}>{status}</Badge></TableCell><TableCell>{d&&!Number.isNaN(d.getTime())?d.toLocaleDateString():"—"}</TableCell><TableCell className="max-w-64 truncate">{String(pick(r,"note","admin_note")??"—")}</TableCell></TableRow>}):<TableRow><TableCell colSpan={6} className="py-10 text-center text-darklink">No withdrawal requests found for this period.</TableCell></TableRow>}</TableBody></Table></div></CardBox>}
